codecov:
  ci:
    - futagoza.visualstudio.com

coverage:
  status:
    project:
      default:
        target: 1
    patch: off

ignore:
  - "**/*.{spec,test}.js"
  - "**/*.eslintrc.js"

parsers:
  javascript:
    enable_partials: yes
