codecov:
  ci:
    - github.com

coverage:
  status:
    project:
      default:
        target: 1
    patch: off

ignore:
  - "**/*.js"
  - "**/*.d.ts"
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "archived/**/*.ts"
